Add code of conduct 1
EddieHubCommunity/EventCalendar pull request #21
Opened 2021-11-05 18:45 UTC by Neeteshking21

2021-11-05 18:49 UTC, mohan-murali commented
Create a new branch and rebase it from main.

2021-11-05 20:26 UTC, CodingSpecies requested changes
@Neeteshking21 do we need the .docker files? Or can they be removed from the commit?

2021-11-05 20:27 UTC, CodingSpecies commented
Sorry for the above comment, I didn't see the other commits.

2021-11-09 08:05 UTC, eddiejaoude commented
Not sure why there are so many other changes in this PR, should only be the code of conduct?

2021-11-09 08:05 UTC, eddiejaoude requested changes
Too many changes, please only include the Code of Conduct

2021-11-19 19:25 UTC, emmalearnscode commented
Do you need any help with this @Neeteshking21 ?

2021-11-20 02:13 UTC, Neeteshking21 commented
Yes, off course.@emmalearnscode

2021-11-20 03:54 UTC, krishguptadev requested changes
Please only add code of conduct, move the rest changes to another PR 🙂

2021-11-20 03:54 UTC, krishguptadev commented on README.md
> -This section has moved here: [https://facebook.github.io/create-react-app/docs/troubleshooting#npm-run-build-fails-to-minify](https://facebook.github.io/create-react-app/docs/troubleshooting#npm-run-
Please revert this change

2021-11-29 17:13 UTC, emmalearnscode commented
Thank you for contributing @Neeteshking21 I see someone else already added a code of conduct to the project and since this pr currently has lots of conflicts I will close it but please feel free to make more PRs in the future :)

2021-11-29 17:13 UTC, closed without merging