Added my event to calendar
EddieHubCommunity/EventCalendar pull request #69
Opened 2021-11-18 05:32 UTC by SahityaRoy

2021-11-19 23:15 UTC, eddiejaoude commented on public/data/SahityaRoy.json
> +  "url": "http://twitter.com/SahityaRoy07",
This should go to the actual event itself not a general link

2021-11-19 23:16 UTC, eddiejaoude commented on public/data/SahityaRoy.json
> +  "start": "2021-11-06T17:00:00",
This event happened many weeks ago already? When is your next event?

2021-11-20 15:45 UTC, krishguptadev requested changes
Please see the comments above 🙂

2021-11-26 13:56 UTC, eddiejaoude commented
Event past, so I will close. Please feel free to create a new PR with up and coming event

2021-11-26 13:56 UTC, closed without merging