added thanks to all the contributors in ``readme.md
EddieHubCommunity/EventCalendar pull request #72
Opened 2021-11-18 12:49 UTC by adityatheoctocatdev

- fixes #47

2021-11-19 02:46 UTC, krishguptadev requested changes

2021-11-19 02:46 UTC, krishguptadev commented on README.md
> +Thanks a lot for spending your time in helping LinkFree grow. Thanks a lot! Keep rocking 🍻
```suggestion
Thanks a lot for spending your time helping EventCalender grow. Thanks a lot! Keep rocking 🍻
```

2021-11-19 02:49 UTC, krishguptadev approved these changes

2021-11-19 02:50 UTC, krishguptadev requested changes

2021-11-19 02:50 UTC, krishguptadev commented on README.md
> +This project needs a ⭐️ from you. Don't forget to leave a star ⭐️
Not sure if we need this line 🤔

2021-11-19 04:34 UTC, krishguptadev approved these changes

2021-11-19 16:21 UTC, Vyvy-vi approved these changes
lgtm!

2021-11-20 12:51 UTC, shreyaansjain06 approved these changes

2021-11-21 13:02 UTC, emmalearnscode commented
This change looks good but there is currently a merge conflict caused by a previous pull request being merged into the same file. If you can fix the merge conflict we can get this merged in.

2021-11-21 13:04 UTC, krishguptadev reviewed
Please check the comments above.

2021-11-22 03:55 UTC, krishguptadev requested changes

2021-11-22 03:55 UTC, krishguptadev commented on README.md
> +Thanks a lot for spending your time helping EventCalender grow. Thanks a lot! Keep rocking 🍻
```suggestion
Thanks a lot for spending your time helping EventCalendar grow. Thanks a lot! Keep rocking 🍻

[![Contributors](https://contrib.rocks/image?repo=EddieHubCommunity/LinkFree)](https://github.com/EddieHubCommunity/LinkFree/graphs/contributors)
```

2021-11-22 03:55 UTC, krishguptadev commented on README.md
> +[contributors](https://github.com/EddieHubCommunity/EventCalendar/graphs/contributors)
```suggestion]
```

2021-11-22 05:07 UTC, krishguptadev requested changes

2021-11-22 05:07 UTC, krishguptadev commented on README.md
> +Thanks a lot for spending your time helping EventCalendar grow. Thanks a lot! Keep rocking 🍻
```suggestion
Thanks a lot for spending your time helping EventCalendar grow. Thanks a lot! Keep rocking 🍻

[![Contributors](https://contrib.rocks/image?repo=EddieHubCommunity/LinkFree)](https://github.com/EddieHubCommunity/LinkFree/graphs/contributors)
```

2021-11-23 18:35 UTC, merged